### PR TITLE
Open up to Laravel Scout 7

### PR DESCRIPTION
**Pull request by xtrasmal**
Just updated Laravel and all packages to the latest version. 
Laravel 6 and Scout 7 can be used with this package. 
Also tested with the TeamTNT scout driver

### CODE REVIEW

**Comment by xtrasmal** [comment]
I'm so bad when creating pull-requests. Sorry for that.

**Comment by KPKoch** [comment]
Would be great if this could be merged, as Laravel is in version 6 a while ago.
Having a medium sized project on laravel doctrine base becomes more and more critical, if the laraveldoctrine is not in active development anymore. Sadly I am not able to support this myself.

**Comment by kfeng0806** [comment]
Please can we merge this PR? @patrickbrouwers

**Comment by patrickbrouwers** [comment]
I'm not a maintainer of Laravel Doctrine anymore, please ask on their Slack for a maintainer to look at this.

**Comment by eigan** [comment]
Sorry for the delay guys :open_mouth: 

Thanks for you contribution @xtrasmal. This is now released with version 0.2.

**Pull request merged**
